name       : kdesignerplugin
version    : 5.36.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.36/kdesignerplugin-5.36.0.tar.xz : 1ba67344b46e1cb0809975f84c667019158e69ae1b884ab3a995ca1d8d434acf
license    : LGPL-2.1
component  : programming
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kplotting-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
