name       : kdesignerplugin
version    : 5.48.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kdesignerplugin-5.48.0.tar.xz : 5450307bb9d0bc369022fd6f7519e419628f5c2bbd7cf266b821fa2b5fdf5ccf
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kplotting-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
