name       : kdesignerplugin
version    : 5.46.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/kdesignerplugin-5.46.0.tar.xz : ca9ca83d741589e2e4fbfcf16973d3e81148d8558cfb0957d265f32af7a1bb87
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kplotting-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
