name       : kdesignerplugin
version    : 5.71.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/portingAids/kdesignerplugin-5.71.0.tar.xz : e77a96c2a6cd518f3040e9366f013f0128200791b6c93c3c5b2310af16fb040b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
