name       : kdesignerplugin
version    : 5.64.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/portingAids/kdesignerplugin-5.64.0.tar.xz : 1ca638ec822d9882f4a865d599ce8ad94785fa890ce73bccd5e78210c4a3d95b
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
