name       : kdesignerplugin
version    : 5.84.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/portingAids/kdesignerplugin-5.84.0.tar.xz : 5d091b325862b41eda9eecaecc4165db45078c507a5dc0e742cc3502a7bca14c
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WebKit)
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
