name       : kdesignerplugin
version    : 5.90.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/portingAids/kdesignerplugin-5.90.0.tar.xz : 388a2e9a2be330c7e90101e4eb2ca30e1a66a76e236e65e56f4a42311cf2faa1
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WebKit)
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
