name       : kdesignerplugin
version    : 5.72.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/portingAids/kdesignerplugin-5.72.0.tar.xz : 4d72036b85800ae096ca2cc5b6c599c4fd922fb86edca8a171d6b9a3ef71b1dc
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
