name       : kdesignerplugin
version    : 5.28.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.28/kdesignerplugin-5.28.0.tar.xz : a30a8275f6c87168bc333d6ae91116d762b31d34b8774ad71057d268ddba698b
license    : LGPL-2.1
component  : programming
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kplotting-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
