name       : kdesignerplugin
version    : 5.40.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kdesignerplugin-5.40.0.tar.xz : 0d57e158e8247a06b148ff9f65c013257b0f374301dd0f05c5a0c70040239403
license    : LGPL-2.1
component  : programming
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kplotting-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
