name       : kdesignerplugin
version    : 5.81.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/portingAids/kdesignerplugin-5.81.0.tar.xz : 4307cd1c3bb681ec1c28cb4399ef952a1966273963f6511eb0b6256d9791f6e5
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WebKit)
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
