name       : kdesignerplugin
version    : 5.65.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/portingAids/kdesignerplugin-5.65.0.tar.xz : e6ba152df5848789cd35f1734dfd3d20f439a21ebba8b96caf747654de42c515
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
