name       : kdesignerplugin
version    : 5.61.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/kdesignerplugin-5.61.0.tar.xz : 6b204dffbb4897f51143650d75383b5a3ddf4254455e5827d316c7b4ee7b3f33
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kplotting-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
