name       : kdesignerplugin
version    : 5.77.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/portingAids/kdesignerplugin-5.77.0.tar.xz : 463fd7997e9177ca5f9b7a6533f8331960e51c6c8b7e88636e12267cd174b823
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
