name       : kdesignerplugin
version    : 5.82.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/portingAids/kdesignerplugin-5.82.0.tar.xz : 4556c3001f6558cf8ecaf9ce98b60bc130099b0af5d35be48561405b778d6f79
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WebKit)
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
