name       : kdesignerplugin
version    : 5.67.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/portingAids/kdesignerplugin-5.67.0.tar.xz : 0b0924dad7bc9cf87a7589dc3bf35a928177dd79e7bce2430193431972c5fc28
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
