name       : kdesignerplugin
version    : 5.59.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kdesignerplugin-5.59.0.tar.xz : b8a13a834fbcc7f4e7e4bb0d4e71ee2846d9660c02f3500b0f14c3a834649d3b
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kio-devel
    - kplotting-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
