name       : kdesignerplugin
version    : 5.88.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.88/portingAids/kdesignerplugin-5.88.0.tar.xz : d90c6245209d52e891755fcf8a35ce40d9de3b9c315c3f4bef8b556270b0154b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Integrating KDE frameworks widgets with Qt Designer
description: |
    Integrating KDE frameworks widgets with Qt Designer.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WebKit)
    - kconfig-devel
    - kcoreaddons-devel
    - kdewebkit-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kplotting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
